// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: .proto/download.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetDownloadUrl requests the download URL for a media item
type GetDownloadUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field1        *GetDownloadUrl_Field1 `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2        *GetDownloadUrl_Field2 `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl) Reset() {
	*x = GetDownloadUrl{}
	mi := &file___proto_download_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl) ProtoMessage() {}

func (x *GetDownloadUrl) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{0}
}

func (x *GetDownloadUrl) GetField1() *GetDownloadUrl_Field1 {
	if x != nil {
		return x.Field1
	}
	return nil
}

func (x *GetDownloadUrl) GetField2() *GetDownloadUrl_Field2 {
	if x != nil {
		return x.Field2
	}
	return nil
}

// GetDownloadUrlResponse contains the download URL for a media item
type GetDownloadUrlResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Field1        *GetDownloadUrlResponse_Field1 `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlResponse) Reset() {
	*x = GetDownloadUrlResponse{}
	mi := &file___proto_download_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlResponse) ProtoMessage() {}

func (x *GetDownloadUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlResponse) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{1}
}

func (x *GetDownloadUrlResponse) GetField1() *GetDownloadUrlResponse_Field1 {
	if x != nil {
		return x.Field1
	}
	return nil
}

type GetDownloadUrl_Field1 struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Field1        *GetDownloadUrl_Field1_Field1Inner `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field1) Reset() {
	*x = GetDownloadUrl_Field1{}
	mi := &file___proto_download_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field1) ProtoMessage() {}

func (x *GetDownloadUrl_Field1) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field1.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field1) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetDownloadUrl_Field1) GetField1() *GetDownloadUrl_Field1_Field1Inner {
	if x != nil {
		return x.Field1
	}
	return nil
}

type GetDownloadUrl_Field2 struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Field1        *GetDownloadUrl_Field2_Field1Type `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field5        *GetDownloadUrl_Field2_Field5Type `protobuf:"bytes,5,opt,name=field5,proto3" json:"field5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field2) Reset() {
	*x = GetDownloadUrl_Field2{}
	mi := &file___proto_download_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field2) ProtoMessage() {}

func (x *GetDownloadUrl_Field2) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field2.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field2) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetDownloadUrl_Field2) GetField1() *GetDownloadUrl_Field2_Field1Type {
	if x != nil {
		return x.Field1
	}
	return nil
}

func (x *GetDownloadUrl_Field2) GetField5() *GetDownloadUrl_Field2_Field5Type {
	if x != nil {
		return x.Field5
	}
	return nil
}

type GetDownloadUrl_Field1_Field1Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaKey      string                 `protobuf:"bytes,1,opt,name=media_key,json=mediaKey,proto3" json:"media_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field1_Field1Inner) Reset() {
	*x = GetDownloadUrl_Field1_Field1Inner{}
	mi := &file___proto_download_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field1_Field1Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field1_Field1Inner) ProtoMessage() {}

func (x *GetDownloadUrl_Field1_Field1Inner) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field1_Field1Inner.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field1_Field1Inner) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *GetDownloadUrl_Field1_Field1Inner) GetMediaKey() string {
	if x != nil {
		return x.MediaKey
	}
	return ""
}

type GetDownloadUrl_Field2_Field1Type struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Field7        *GetDownloadUrl_Field2_Field1Type_Field7Type `protobuf:"bytes,7,opt,name=field7,proto3" json:"field7,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field2_Field1Type) Reset() {
	*x = GetDownloadUrl_Field2_Field1Type{}
	mi := &file___proto_download_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field2_Field1Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field2_Field1Type) ProtoMessage() {}

func (x *GetDownloadUrl_Field2_Field1Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field2_Field1Type.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field2_Field1Type) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *GetDownloadUrl_Field2_Field1Type) GetField7() *GetDownloadUrl_Field2_Field1Type_Field7Type {
	if x != nil {
		return x.Field7
	}
	return nil
}

type GetDownloadUrl_Field2_Field5Type struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	Field2        *GetDownloadUrl_Field2_Field5Type_Field2Type  `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	Field3        *GetDownloadUrl_Field2_Field5Type_Field3Type  `protobuf:"bytes,3,opt,name=field3,proto3" json:"field3,omitempty"`
	Field5        *GetDownloadUrl_Field2_Field5Type_Field5Inner `protobuf:"bytes,5,opt,name=field5,proto3" json:"field5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field2_Field5Type) Reset() {
	*x = GetDownloadUrl_Field2_Field5Type{}
	mi := &file___proto_download_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field2_Field5Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field2_Field5Type) ProtoMessage() {}

func (x *GetDownloadUrl_Field2_Field5Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field2_Field5Type.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field2_Field5Type) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *GetDownloadUrl_Field2_Field5Type) GetField2() *GetDownloadUrl_Field2_Field5Type_Field2Type {
	if x != nil {
		return x.Field2
	}
	return nil
}

func (x *GetDownloadUrl_Field2_Field5Type) GetField3() *GetDownloadUrl_Field2_Field5Type_Field3Type {
	if x != nil {
		return x.Field3
	}
	return nil
}

func (x *GetDownloadUrl_Field2_Field5Type) GetField5() *GetDownloadUrl_Field2_Field5Type_Field5Inner {
	if x != nil {
		return x.Field5
	}
	return nil
}

type GetDownloadUrl_Field2_Field1Type_Field7Type struct {
	state         protoimpl.MessageState                                  `protogen:"open.v1"`
	Field2        *GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field2_Field1Type_Field7Type) Reset() {
	*x = GetDownloadUrl_Field2_Field1Type_Field7Type{}
	mi := &file___proto_download_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field2_Field1Type_Field7Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field2_Field1Type_Field7Type) ProtoMessage() {}

func (x *GetDownloadUrl_Field2_Field1Type_Field7Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field2_Field1Type_Field7Type.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field2_Field1Type_Field7Type) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{0, 1, 0, 0}
}

func (x *GetDownloadUrl_Field2_Field1Type_Field7Type) GetField2() *GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type {
	if x != nil {
		return x.Field2
	}
	return nil
}

type GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type) Reset() {
	*x = GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type{}
	mi := &file___proto_download_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type) ProtoMessage() {}

func (x *GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{0, 1, 0, 0, 0}
}

type GetDownloadUrl_Field2_Field5Type_Field2Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field2_Field5Type_Field2Type) Reset() {
	*x = GetDownloadUrl_Field2_Field5Type_Field2Type{}
	mi := &file___proto_download_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field2_Field5Type_Field2Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field2_Field5Type_Field2Type) ProtoMessage() {}

func (x *GetDownloadUrl_Field2_Field5Type_Field2Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field2_Field5Type_Field2Type.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field2_Field5Type_Field2Type) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{0, 1, 1, 0}
}

type GetDownloadUrl_Field2_Field5Type_Field3Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field2_Field5Type_Field3Type) Reset() {
	*x = GetDownloadUrl_Field2_Field5Type_Field3Type{}
	mi := &file___proto_download_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field2_Field5Type_Field3Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field2_Field5Type_Field3Type) ProtoMessage() {}

func (x *GetDownloadUrl_Field2_Field5Type_Field3Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field2_Field5Type_Field3Type.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field2_Field5Type_Field3Type) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{0, 1, 1, 1}
}

type GetDownloadUrl_Field2_Field5Type_Field5Inner struct {
	state         protoimpl.MessageState                                   `protogen:"open.v1"`
	Field1        *GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field3        int64                                                    `protobuf:"varint,3,opt,name=field3,proto3" json:"field3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field2_Field5Type_Field5Inner) Reset() {
	*x = GetDownloadUrl_Field2_Field5Type_Field5Inner{}
	mi := &file___proto_download_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field2_Field5Type_Field5Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field2_Field5Type_Field5Inner) ProtoMessage() {}

func (x *GetDownloadUrl_Field2_Field5Type_Field5Inner) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field2_Field5Type_Field5Inner.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field2_Field5Type_Field5Inner) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{0, 1, 1, 2}
}

func (x *GetDownloadUrl_Field2_Field5Type_Field5Inner) GetField1() *GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type {
	if x != nil {
		return x.Field1
	}
	return nil
}

func (x *GetDownloadUrl_Field2_Field5Type_Field5Inner) GetField3() int64 {
	if x != nil {
		return x.Field3
	}
	return 0
}

type GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type) Reset() {
	*x = GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type{}
	mi := &file___proto_download_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type) ProtoMessage() {}

func (x *GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{0, 1, 1, 2, 0}
}

type GetDownloadUrlResponse_Field1 struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	MediaKey      string                                       `protobuf:"bytes,1,opt,name=media_key,json=mediaKey,proto3" json:"media_key,omitempty"`    // The media key
	Metadata      *GetDownloadUrlResponse_Field1_MediaMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`                    // File metadata
	Urls          *GetDownloadUrlResponse_Field1_URLs          `protobuf:"bytes,5,opt,name=urls,proto3" json:"urls,omitempty"`                            // Download URLs
	OwnerInfo     *GetDownloadUrlResponse_Field1_OwnerInfo     `protobuf:"bytes,6,opt,name=owner_info,json=ownerInfo,proto3" json:"owner_info,omitempty"` // Owner/user info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlResponse_Field1) Reset() {
	*x = GetDownloadUrlResponse_Field1{}
	mi := &file___proto_download_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlResponse_Field1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlResponse_Field1) ProtoMessage() {}

func (x *GetDownloadUrlResponse_Field1) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlResponse_Field1.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlResponse_Field1) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetDownloadUrlResponse_Field1) GetMediaKey() string {
	if x != nil {
		return x.MediaKey
	}
	return ""
}

func (x *GetDownloadUrlResponse_Field1) GetMetadata() *GetDownloadUrlResponse_Field1_MediaMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetDownloadUrlResponse_Field1) GetUrls() *GetDownloadUrlResponse_Field1_URLs {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *GetDownloadUrlResponse_Field1) GetOwnerInfo() *GetDownloadUrlResponse_Field1_OwnerInfo {
	if x != nil {
		return x.OwnerInfo
	}
	return nil
}

type GetDownloadUrlResponse_Field1_MediaMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Filename          string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`                                              // Original filename
	CreatedAt         int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                          // Creation time (Unix ms)
	Field8            int64                  `protobuf:"varint,8,opt,name=field8,proto3" json:"field8,omitempty"`                                                 // Unknown
	UploadedAt        int64                  `protobuf:"varint,9,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`                       // Upload time (Unix ms)
	FileSize          int64                  `protobuf:"varint,10,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`                            // File size in bytes
	QualityPercentage int64                  `protobuf:"varint,11,opt,name=quality_percentage,json=qualityPercentage,proto3" json:"quality_percentage,omitempty"` // Quality percentage (0-100)
	MediaType         int64                  `protobuf:"varint,19,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`                         // Media type (1=photo, 2=video)
	Field24           int64                  `protobuf:"varint,24,opt,name=field24,proto3" json:"field24,omitempty"`                                              // Unknown
	Field26           int64                  `protobuf:"varint,26,opt,name=field26,proto3" json:"field26,omitempty"`                                              // Unknown
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetDownloadUrlResponse_Field1_MediaMetadata) Reset() {
	*x = GetDownloadUrlResponse_Field1_MediaMetadata{}
	mi := &file___proto_download_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlResponse_Field1_MediaMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlResponse_Field1_MediaMetadata) ProtoMessage() {}

func (x *GetDownloadUrlResponse_Field1_MediaMetadata) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlResponse_Field1_MediaMetadata.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlResponse_Field1_MediaMetadata) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *GetDownloadUrlResponse_Field1_MediaMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetDownloadUrlResponse_Field1_MediaMetadata) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetDownloadUrlResponse_Field1_MediaMetadata) GetField8() int64 {
	if x != nil {
		return x.Field8
	}
	return 0
}

func (x *GetDownloadUrlResponse_Field1_MediaMetadata) GetUploadedAt() int64 {
	if x != nil {
		return x.UploadedAt
	}
	return 0
}

func (x *GetDownloadUrlResponse_Field1_MediaMetadata) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *GetDownloadUrlResponse_Field1_MediaMetadata) GetQualityPercentage() int64 {
	if x != nil {
		return x.QualityPercentage
	}
	return 0
}

func (x *GetDownloadUrlResponse_Field1_MediaMetadata) GetMediaType() int64 {
	if x != nil {
		return x.MediaType
	}
	return 0
}

func (x *GetDownloadUrlResponse_Field1_MediaMetadata) GetField24() int64 {
	if x != nil {
		return x.Field24
	}
	return 0
}

func (x *GetDownloadUrlResponse_Field1_MediaMetadata) GetField26() int64 {
	if x != nil {
		return x.Field26
	}
	return 0
}

type GetDownloadUrlResponse_Field1_OwnerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"` // Owner user ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlResponse_Field1_OwnerInfo) Reset() {
	*x = GetDownloadUrlResponse_Field1_OwnerInfo{}
	mi := &file___proto_download_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlResponse_Field1_OwnerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlResponse_Field1_OwnerInfo) ProtoMessage() {}

func (x *GetDownloadUrlResponse_Field1_OwnerInfo) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlResponse_Field1_OwnerInfo.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlResponse_Field1_OwnerInfo) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *GetDownloadUrlResponse_Field1_OwnerInfo) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type GetDownloadUrlResponse_Field1_URLs struct {
	state         protoimpl.MessageState                           `protogen:"open.v1"`
	IsEdited      int64                                            `protobuf:"varint,1,opt,name=is_edited,json=isEdited,proto3" json:"is_edited,omitempty"` // 1 if edited version exists
	DownloadUrls  *GetDownloadUrlResponse_Field1_URLs_DownloadUrls `protobuf:"bytes,2,opt,name=download_urls,json=downloadUrls,proto3" json:"download_urls,omitempty"`
	Field3        *GetDownloadUrlResponse_Field1_URLs_Field3       `protobuf:"bytes,3,opt,name=field3,proto3" json:"field3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlResponse_Field1_URLs) Reset() {
	*x = GetDownloadUrlResponse_Field1_URLs{}
	mi := &file___proto_download_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlResponse_Field1_URLs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlResponse_Field1_URLs) ProtoMessage() {}

func (x *GetDownloadUrlResponse_Field1_URLs) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlResponse_Field1_URLs.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlResponse_Field1_URLs) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{1, 0, 2}
}

func (x *GetDownloadUrlResponse_Field1_URLs) GetIsEdited() int64 {
	if x != nil {
		return x.IsEdited
	}
	return 0
}

func (x *GetDownloadUrlResponse_Field1_URLs) GetDownloadUrls() *GetDownloadUrlResponse_Field1_URLs_DownloadUrls {
	if x != nil {
		return x.DownloadUrls
	}
	return nil
}

func (x *GetDownloadUrlResponse_Field1_URLs) GetField3() *GetDownloadUrlResponse_Field1_URLs_Field3 {
	if x != nil {
		return x.Field3
	}
	return nil
}

type GetDownloadUrlResponse_Field1_URLs_DownloadUrls struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EditedUrl     string                 `protobuf:"bytes,5,opt,name=edited_url,json=editedUrl,proto3" json:"edited_url,omitempty"`       // Download URL for edited version
	OriginalUrl   string                 `protobuf:"bytes,6,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"` // Download URL for original version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlResponse_Field1_URLs_DownloadUrls) Reset() {
	*x = GetDownloadUrlResponse_Field1_URLs_DownloadUrls{}
	mi := &file___proto_download_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlResponse_Field1_URLs_DownloadUrls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlResponse_Field1_URLs_DownloadUrls) ProtoMessage() {}

func (x *GetDownloadUrlResponse_Field1_URLs_DownloadUrls) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlResponse_Field1_URLs_DownloadUrls.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlResponse_Field1_URLs_DownloadUrls) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{1, 0, 2, 0}
}

func (x *GetDownloadUrlResponse_Field1_URLs_DownloadUrls) GetEditedUrl() string {
	if x != nil {
		return x.EditedUrl
	}
	return ""
}

func (x *GetDownloadUrlResponse_Field1_URLs_DownloadUrls) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type GetDownloadUrlResponse_Field1_URLs_Field3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field1        string                 `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field3        int64                  `protobuf:"varint,3,opt,name=field3,proto3" json:"field3,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,5,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlResponse_Field1_URLs_Field3) Reset() {
	*x = GetDownloadUrlResponse_Field1_URLs_Field3{}
	mi := &file___proto_download_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlResponse_Field1_URLs_Field3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlResponse_Field1_URLs_Field3) ProtoMessage() {}

func (x *GetDownloadUrlResponse_Field1_URLs_Field3) ProtoReflect() protoreflect.Message {
	mi := &file___proto_download_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlResponse_Field1_URLs_Field3.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlResponse_Field1_URLs_Field3) Descriptor() ([]byte, []int) {
	return file___proto_download_proto_rawDescGZIP(), []int{1, 0, 2, 1}
}

func (x *GetDownloadUrlResponse_Field1_URLs_Field3) GetField1() string {
	if x != nil {
		return x.Field1
	}
	return ""
}

func (x *GetDownloadUrlResponse_Field1_URLs_Field3) GetField3() int64 {
	if x != nil {
		return x.Field3
	}
	return 0
}

func (x *GetDownloadUrlResponse_Field1_URLs_Field3) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

var File___proto_download_proto protoreflect.FileDescriptor

const file___proto_download_proto_rawDesc = "" +
	"\n" +
	"\x15.proto/download.proto\"\xab\a\n" +
	"\x0eGetDownloadUrl\x12.\n" +
	"\x06field1\x18\x01 \x01(\v2\x16.GetDownloadUrl.Field1R\x06field1\x12.\n" +
	"\x06field2\x18\x02 \x01(\v2\x16.GetDownloadUrl.Field2R\x06field2\x1ap\n" +
	"\x06Field1\x12:\n" +
	"\x06field1\x18\x01 \x01(\v2\".GetDownloadUrl.Field1.Field1InnerR\x06field1\x1a*\n" +
	"\vField1Inner\x12\x1b\n" +
	"\tmedia_key\x18\x01 \x01(\tR\bmediaKey\x1a\xc6\x05\n" +
	"\x06Field2\x129\n" +
	"\x06field1\x18\x01 \x01(\v2!.GetDownloadUrl.Field2.Field1TypeR\x06field1\x129\n" +
	"\x06field5\x18\x05 \x01(\v2!.GetDownloadUrl.Field2.Field5TypeR\x06field5\x1a\xbf\x01\n" +
	"\n" +
	"Field1Type\x12D\n" +
	"\x06field7\x18\a \x01(\v2,.GetDownloadUrl.Field2.Field1Type.Field7TypeR\x06field7\x1ak\n" +
	"\n" +
	"Field7Type\x12O\n" +
	"\x06field2\x18\x02 \x01(\v27.GetDownloadUrl.Field2.Field1Type.Field7Type.Field2TypeR\x06field2\x1a\f\n" +
	"\n" +
	"Field2Type\x1a\x83\x03\n" +
	"\n" +
	"Field5Type\x12D\n" +
	"\x06field2\x18\x02 \x01(\v2,.GetDownloadUrl.Field2.Field5Type.Field2TypeR\x06field2\x12D\n" +
	"\x06field3\x18\x03 \x01(\v2,.GetDownloadUrl.Field2.Field5Type.Field3TypeR\x06field3\x12E\n" +
	"\x06field5\x18\x05 \x01(\v2-.GetDownloadUrl.Field2.Field5Type.Field5InnerR\x06field5\x1a\f\n" +
	"\n" +
	"Field2Type\x1a\f\n" +
	"\n" +
	"Field3Type\x1a\x85\x01\n" +
	"\vField5Inner\x12P\n" +
	"\x06field1\x18\x01 \x01(\v28.GetDownloadUrl.Field2.Field5Type.Field5Inner.Field1TypeR\x06field1\x12\x16\n" +
	"\x06field3\x18\x03 \x01(\x03R\x06field3\x1a\f\n" +
	"\n" +
	"Field1Type\"\x81\b\n" +
	"\x16GetDownloadUrlResponse\x126\n" +
	"\x06field1\x18\x01 \x01(\v2\x1e.GetDownloadUrlResponse.Field1R\x06field1\x1a\xae\a\n" +
	"\x06Field1\x12\x1b\n" +
	"\tmedia_key\x18\x01 \x01(\tR\bmediaKey\x12H\n" +
	"\bmetadata\x18\x02 \x01(\v2,.GetDownloadUrlResponse.Field1.MediaMetadataR\bmetadata\x127\n" +
	"\x04urls\x18\x05 \x01(\v2#.GetDownloadUrlResponse.Field1.URLsR\x04urls\x12G\n" +
	"\n" +
	"owner_info\x18\x06 \x01(\v2(.GetDownloadUrlResponse.Field1.OwnerInfoR\townerInfo\x1a\xa2\x02\n" +
	"\rMediaMetadata\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x16\n" +
	"\x06field8\x18\b \x01(\x03R\x06field8\x12\x1f\n" +
	"\vuploaded_at\x18\t \x01(\x03R\n" +
	"uploadedAt\x12\x1b\n" +
	"\tfile_size\x18\n" +
	" \x01(\x03R\bfileSize\x12-\n" +
	"\x12quality_percentage\x18\v \x01(\x03R\x11qualityPercentage\x12\x1d\n" +
	"\n" +
	"media_type\x18\x13 \x01(\x03R\tmediaType\x12\x18\n" +
	"\afield24\x18\x18 \x01(\x03R\afield24\x12\x18\n" +
	"\afield26\x18\x1a \x01(\x03R\afield26\x1a&\n" +
	"\tOwnerInfo\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x1a\xed\x02\n" +
	"\x04URLs\x12\x1b\n" +
	"\tis_edited\x18\x01 \x01(\x03R\bisEdited\x12U\n" +
	"\rdownload_urls\x18\x02 \x01(\v20.GetDownloadUrlResponse.Field1.URLs.DownloadUrlsR\fdownloadUrls\x12B\n" +
	"\x06field3\x18\x03 \x01(\v2*.GetDownloadUrlResponse.Field1.URLs.Field3R\x06field3\x1aP\n" +
	"\fDownloadUrls\x12\x1d\n" +
	"\n" +
	"edited_url\x18\x05 \x01(\tR\teditedUrl\x12!\n" +
	"\foriginal_url\x18\x06 \x01(\tR\voriginalUrl\x1a[\n" +
	"\x06Field3\x12\x16\n" +
	"\x06field1\x18\x01 \x01(\tR\x06field1\x12\x16\n" +
	"\x06field3\x18\x03 \x01(\x03R\x06field3\x12!\n" +
	"\fdownload_url\x18\x05 \x01(\tR\vdownloadUrlB.Z,github.com/viperadnan-git/go-gpm/internal/pbb\x06proto3"

var (
	file___proto_download_proto_rawDescOnce sync.Once
	file___proto_download_proto_rawDescData []byte
)

func file___proto_download_proto_rawDescGZIP() []byte {
	file___proto_download_proto_rawDescOnce.Do(func() {
		file___proto_download_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file___proto_download_proto_rawDesc), len(file___proto_download_proto_rawDesc)))
	})
	return file___proto_download_proto_rawDescData
}

var file___proto_download_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file___proto_download_proto_goTypes = []any{
	(*GetDownloadUrl)(nil),                                          // 0: GetDownloadUrl
	(*GetDownloadUrlResponse)(nil),                                  // 1: GetDownloadUrlResponse
	(*GetDownloadUrl_Field1)(nil),                                   // 2: GetDownloadUrl.Field1
	(*GetDownloadUrl_Field2)(nil),                                   // 3: GetDownloadUrl.Field2
	(*GetDownloadUrl_Field1_Field1Inner)(nil),                       // 4: GetDownloadUrl.Field1.Field1Inner
	(*GetDownloadUrl_Field2_Field1Type)(nil),                        // 5: GetDownloadUrl.Field2.Field1Type
	(*GetDownloadUrl_Field2_Field5Type)(nil),                        // 6: GetDownloadUrl.Field2.Field5Type
	(*GetDownloadUrl_Field2_Field1Type_Field7Type)(nil),             // 7: GetDownloadUrl.Field2.Field1Type.Field7Type
	(*GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type)(nil),  // 8: GetDownloadUrl.Field2.Field1Type.Field7Type.Field2Type
	(*GetDownloadUrl_Field2_Field5Type_Field2Type)(nil),             // 9: GetDownloadUrl.Field2.Field5Type.Field2Type
	(*GetDownloadUrl_Field2_Field5Type_Field3Type)(nil),             // 10: GetDownloadUrl.Field2.Field5Type.Field3Type
	(*GetDownloadUrl_Field2_Field5Type_Field5Inner)(nil),            // 11: GetDownloadUrl.Field2.Field5Type.Field5Inner
	(*GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type)(nil), // 12: GetDownloadUrl.Field2.Field5Type.Field5Inner.Field1Type
	(*GetDownloadUrlResponse_Field1)(nil),                           // 13: GetDownloadUrlResponse.Field1
	(*GetDownloadUrlResponse_Field1_MediaMetadata)(nil),             // 14: GetDownloadUrlResponse.Field1.MediaMetadata
	(*GetDownloadUrlResponse_Field1_OwnerInfo)(nil),                 // 15: GetDownloadUrlResponse.Field1.OwnerInfo
	(*GetDownloadUrlResponse_Field1_URLs)(nil),                      // 16: GetDownloadUrlResponse.Field1.URLs
	(*GetDownloadUrlResponse_Field1_URLs_DownloadUrls)(nil),         // 17: GetDownloadUrlResponse.Field1.URLs.DownloadUrls
	(*GetDownloadUrlResponse_Field1_URLs_Field3)(nil),               // 18: GetDownloadUrlResponse.Field1.URLs.Field3
}
var file___proto_download_proto_depIdxs = []int32{
	2,  // 0: GetDownloadUrl.field1:type_name -> GetDownloadUrl.Field1
	3,  // 1: GetDownloadUrl.field2:type_name -> GetDownloadUrl.Field2
	13, // 2: GetDownloadUrlResponse.field1:type_name -> GetDownloadUrlResponse.Field1
	4,  // 3: GetDownloadUrl.Field1.field1:type_name -> GetDownloadUrl.Field1.Field1Inner
	5,  // 4: GetDownloadUrl.Field2.field1:type_name -> GetDownloadUrl.Field2.Field1Type
	6,  // 5: GetDownloadUrl.Field2.field5:type_name -> GetDownloadUrl.Field2.Field5Type
	7,  // 6: GetDownloadUrl.Field2.Field1Type.field7:type_name -> GetDownloadUrl.Field2.Field1Type.Field7Type
	9,  // 7: GetDownloadUrl.Field2.Field5Type.field2:type_name -> GetDownloadUrl.Field2.Field5Type.Field2Type
	10, // 8: GetDownloadUrl.Field2.Field5Type.field3:type_name -> GetDownloadUrl.Field2.Field5Type.Field3Type
	11, // 9: GetDownloadUrl.Field2.Field5Type.field5:type_name -> GetDownloadUrl.Field2.Field5Type.Field5Inner
	8,  // 10: GetDownloadUrl.Field2.Field1Type.Field7Type.field2:type_name -> GetDownloadUrl.Field2.Field1Type.Field7Type.Field2Type
	12, // 11: GetDownloadUrl.Field2.Field5Type.Field5Inner.field1:type_name -> GetDownloadUrl.Field2.Field5Type.Field5Inner.Field1Type
	14, // 12: GetDownloadUrlResponse.Field1.metadata:type_name -> GetDownloadUrlResponse.Field1.MediaMetadata
	16, // 13: GetDownloadUrlResponse.Field1.urls:type_name -> GetDownloadUrlResponse.Field1.URLs
	15, // 14: GetDownloadUrlResponse.Field1.owner_info:type_name -> GetDownloadUrlResponse.Field1.OwnerInfo
	17, // 15: GetDownloadUrlResponse.Field1.URLs.download_urls:type_name -> GetDownloadUrlResponse.Field1.URLs.DownloadUrls
	18, // 16: GetDownloadUrlResponse.Field1.URLs.field3:type_name -> GetDownloadUrlResponse.Field1.URLs.Field3
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file___proto_download_proto_init() }
func file___proto_download_proto_init() {
	if File___proto_download_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file___proto_download_proto_rawDesc), len(file___proto_download_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file___proto_download_proto_goTypes,
		DependencyIndexes: file___proto_download_proto_depIdxs,
		MessageInfos:      file___proto_download_proto_msgTypes,
	}.Build()
	File___proto_download_proto = out.File
	file___proto_download_proto_goTypes = nil
	file___proto_download_proto_depIdxs = nil
}
