// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: .proto/hash_lookup.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FindMediaByHashRequest checks if media with given hash already exists
type FindMediaByHashRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Field1        *FindMediaByHashRequestField1Type `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMediaByHashRequest) Reset() {
	*x = FindMediaByHashRequest{}
	mi := &file___proto_hash_lookup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMediaByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMediaByHashRequest) ProtoMessage() {}

func (x *FindMediaByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_hash_lookup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMediaByHashRequest.ProtoReflect.Descriptor instead.
func (*FindMediaByHashRequest) Descriptor() ([]byte, []int) {
	return file___proto_hash_lookup_proto_rawDescGZIP(), []int{0}
}

func (x *FindMediaByHashRequest) GetField1() *FindMediaByHashRequestField1Type {
	if x != nil {
		return x.Field1
	}
	return nil
}

// FindMediaByHashResponse contains matching media if hash exists
type FindMediaByHashResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Field1        *FindMediaByHashResponseField1Type `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMediaByHashResponse) Reset() {
	*x = FindMediaByHashResponse{}
	mi := &file___proto_hash_lookup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMediaByHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMediaByHashResponse) ProtoMessage() {}

func (x *FindMediaByHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file___proto_hash_lookup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMediaByHashResponse.ProtoReflect.Descriptor instead.
func (*FindMediaByHashResponse) Descriptor() ([]byte, []int) {
	return file___proto_hash_lookup_proto_rawDescGZIP(), []int{1}
}

func (x *FindMediaByHashResponse) GetField1() *FindMediaByHashResponseField1Type {
	if x != nil {
		return x.Field1
	}
	return nil
}

type FindMediaByHashRequestField1Type struct {
	state         protoimpl.MessageState                      `protogen:"open.v1"`
	Field1        *FindMediaByHashRequestField1TypeField1Type `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2        *FindMediaByHashRequestField1TypeField2Type `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMediaByHashRequestField1Type) Reset() {
	*x = FindMediaByHashRequestField1Type{}
	mi := &file___proto_hash_lookup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMediaByHashRequestField1Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMediaByHashRequestField1Type) ProtoMessage() {}

func (x *FindMediaByHashRequestField1Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_hash_lookup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMediaByHashRequestField1Type.ProtoReflect.Descriptor instead.
func (*FindMediaByHashRequestField1Type) Descriptor() ([]byte, []int) {
	return file___proto_hash_lookup_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FindMediaByHashRequestField1Type) GetField1() *FindMediaByHashRequestField1TypeField1Type {
	if x != nil {
		return x.Field1
	}
	return nil
}

func (x *FindMediaByHashRequestField1Type) GetField2() *FindMediaByHashRequestField1TypeField2Type {
	if x != nil {
		return x.Field2
	}
	return nil
}

type FindMediaByHashRequestField1TypeField1Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha1Hash      []byte                 `protobuf:"bytes,1,opt,name=sha1Hash,proto3" json:"sha1Hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMediaByHashRequestField1TypeField1Type) Reset() {
	*x = FindMediaByHashRequestField1TypeField1Type{}
	mi := &file___proto_hash_lookup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMediaByHashRequestField1TypeField1Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMediaByHashRequestField1TypeField1Type) ProtoMessage() {}

func (x *FindMediaByHashRequestField1TypeField1Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_hash_lookup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMediaByHashRequestField1TypeField1Type.ProtoReflect.Descriptor instead.
func (*FindMediaByHashRequestField1TypeField1Type) Descriptor() ([]byte, []int) {
	return file___proto_hash_lookup_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *FindMediaByHashRequestField1TypeField1Type) GetSha1Hash() []byte {
	if x != nil {
		return x.Sha1Hash
	}
	return nil
}

type FindMediaByHashRequestField1TypeField2Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMediaByHashRequestField1TypeField2Type) Reset() {
	*x = FindMediaByHashRequestField1TypeField2Type{}
	mi := &file___proto_hash_lookup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMediaByHashRequestField1TypeField2Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMediaByHashRequestField1TypeField2Type) ProtoMessage() {}

func (x *FindMediaByHashRequestField1TypeField2Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_hash_lookup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMediaByHashRequestField1TypeField2Type.ProtoReflect.Descriptor instead.
func (*FindMediaByHashRequestField1TypeField2Type) Descriptor() ([]byte, []int) {
	return file___proto_hash_lookup_proto_rawDescGZIP(), []int{0, 0, 1}
}

type FindMediaByHashResponseField1Type struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Field2        *FindMediaByHashResponseField1TypeField2Type `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMediaByHashResponseField1Type) Reset() {
	*x = FindMediaByHashResponseField1Type{}
	mi := &file___proto_hash_lookup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMediaByHashResponseField1Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMediaByHashResponseField1Type) ProtoMessage() {}

func (x *FindMediaByHashResponseField1Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_hash_lookup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMediaByHashResponseField1Type.ProtoReflect.Descriptor instead.
func (*FindMediaByHashResponseField1Type) Descriptor() ([]byte, []int) {
	return file___proto_hash_lookup_proto_rawDescGZIP(), []int{1, 0}
}

func (x *FindMediaByHashResponseField1Type) GetField2() *FindMediaByHashResponseField1TypeField2Type {
	if x != nil {
		return x.Field2
	}
	return nil
}

type FindMediaByHashResponseField1TypeField2Type struct {
	state         protoimpl.MessageState                                 `protogen:"open.v1"`
	Field1        *FindMediaByHashResponseField1TypeField2TypeField1Type `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2        *FindMediaByHashResponseField1TypeField2TypeField2Type `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMediaByHashResponseField1TypeField2Type) Reset() {
	*x = FindMediaByHashResponseField1TypeField2Type{}
	mi := &file___proto_hash_lookup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMediaByHashResponseField1TypeField2Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMediaByHashResponseField1TypeField2Type) ProtoMessage() {}

func (x *FindMediaByHashResponseField1TypeField2Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_hash_lookup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMediaByHashResponseField1TypeField2Type.ProtoReflect.Descriptor instead.
func (*FindMediaByHashResponseField1TypeField2Type) Descriptor() ([]byte, []int) {
	return file___proto_hash_lookup_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *FindMediaByHashResponseField1TypeField2Type) GetField1() *FindMediaByHashResponseField1TypeField2TypeField1Type {
	if x != nil {
		return x.Field1
	}
	return nil
}

func (x *FindMediaByHashResponseField1TypeField2Type) GetField2() *FindMediaByHashResponseField1TypeField2TypeField2Type {
	if x != nil {
		return x.Field2
	}
	return nil
}

type FindMediaByHashResponseField1TypeField2TypeField1Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha1Hash      []byte                 `protobuf:"bytes,1,opt,name=sha1_hash,json=sha1Hash,proto3" json:"sha1_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMediaByHashResponseField1TypeField2TypeField1Type) Reset() {
	*x = FindMediaByHashResponseField1TypeField2TypeField1Type{}
	mi := &file___proto_hash_lookup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMediaByHashResponseField1TypeField2TypeField1Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMediaByHashResponseField1TypeField2TypeField1Type) ProtoMessage() {}

func (x *FindMediaByHashResponseField1TypeField2TypeField1Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_hash_lookup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMediaByHashResponseField1TypeField2TypeField1Type.ProtoReflect.Descriptor instead.
func (*FindMediaByHashResponseField1TypeField2TypeField1Type) Descriptor() ([]byte, []int) {
	return file___proto_hash_lookup_proto_rawDescGZIP(), []int{1, 0, 0, 0}
}

func (x *FindMediaByHashResponseField1TypeField2TypeField1Type) GetSha1Hash() []byte {
	if x != nil {
		return x.Sha1Hash
	}
	return nil
}

type FindMediaByHashResponseField1TypeField2TypeField2Type struct {
	state         protoimpl.MessageState                                           `protogen:"open.v1"`
	MediaKey      string                                                           `protobuf:"bytes,1,opt,name=media_key,json=mediaKey,proto3" json:"media_key,omitempty"`
	Field6        *FindMediaByHashResponseField1TypeField2TypeField2TypeField6Type `protobuf:"bytes,6,opt,name=field6,proto3" json:"field6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMediaByHashResponseField1TypeField2TypeField2Type) Reset() {
	*x = FindMediaByHashResponseField1TypeField2TypeField2Type{}
	mi := &file___proto_hash_lookup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMediaByHashResponseField1TypeField2TypeField2Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMediaByHashResponseField1TypeField2TypeField2Type) ProtoMessage() {}

func (x *FindMediaByHashResponseField1TypeField2TypeField2Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_hash_lookup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMediaByHashResponseField1TypeField2TypeField2Type.ProtoReflect.Descriptor instead.
func (*FindMediaByHashResponseField1TypeField2TypeField2Type) Descriptor() ([]byte, []int) {
	return file___proto_hash_lookup_proto_rawDescGZIP(), []int{1, 0, 0, 1}
}

func (x *FindMediaByHashResponseField1TypeField2TypeField2Type) GetMediaKey() string {
	if x != nil {
		return x.MediaKey
	}
	return ""
}

func (x *FindMediaByHashResponseField1TypeField2TypeField2Type) GetField6() *FindMediaByHashResponseField1TypeField2TypeField2TypeField6Type {
	if x != nil {
		return x.Field6
	}
	return nil
}

type FindMediaByHashResponseField1TypeField2TypeField2TypeField6Type struct {
	state         protoimpl.MessageState                                                     `protogen:"open.v1"`
	MediaKey      string                                                                     `protobuf:"bytes,1,opt,name=media_key,json=mediaKey,proto3" json:"media_key,omitempty"`
	Field2        *FindMediaByHashResponseField1TypeField2TypeField2TypeField6TypeField2Type `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMediaByHashResponseField1TypeField2TypeField2TypeField6Type) Reset() {
	*x = FindMediaByHashResponseField1TypeField2TypeField2TypeField6Type{}
	mi := &file___proto_hash_lookup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMediaByHashResponseField1TypeField2TypeField2TypeField6Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMediaByHashResponseField1TypeField2TypeField2TypeField6Type) ProtoMessage() {}

func (x *FindMediaByHashResponseField1TypeField2TypeField2TypeField6Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_hash_lookup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMediaByHashResponseField1TypeField2TypeField2TypeField6Type.ProtoReflect.Descriptor instead.
func (*FindMediaByHashResponseField1TypeField2TypeField2TypeField6Type) Descriptor() ([]byte, []int) {
	return file___proto_hash_lookup_proto_rawDescGZIP(), []int{1, 0, 0, 1, 0}
}

func (x *FindMediaByHashResponseField1TypeField2TypeField2TypeField6Type) GetMediaKey() string {
	if x != nil {
		return x.MediaKey
	}
	return ""
}

func (x *FindMediaByHashResponseField1TypeField2TypeField2TypeField6Type) GetField2() *FindMediaByHashResponseField1TypeField2TypeField2TypeField6TypeField2Type {
	if x != nil {
		return x.Field2
	}
	return nil
}

type FindMediaByHashResponseField1TypeField2TypeField2TypeField6TypeField2Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field1        string                 `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field3        string                 `protobuf:"bytes,3,opt,name=field3,proto3" json:"field3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMediaByHashResponseField1TypeField2TypeField2TypeField6TypeField2Type) Reset() {
	*x = FindMediaByHashResponseField1TypeField2TypeField2TypeField6TypeField2Type{}
	mi := &file___proto_hash_lookup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMediaByHashResponseField1TypeField2TypeField2TypeField6TypeField2Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMediaByHashResponseField1TypeField2TypeField2TypeField6TypeField2Type) ProtoMessage() {}

func (x *FindMediaByHashResponseField1TypeField2TypeField2TypeField6TypeField2Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_hash_lookup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMediaByHashResponseField1TypeField2TypeField2TypeField6TypeField2Type.ProtoReflect.Descriptor instead.
func (*FindMediaByHashResponseField1TypeField2TypeField2TypeField6TypeField2Type) Descriptor() ([]byte, []int) {
	return file___proto_hash_lookup_proto_rawDescGZIP(), []int{1, 0, 0, 1, 0, 0}
}

func (x *FindMediaByHashResponseField1TypeField2TypeField2TypeField6TypeField2Type) GetField1() string {
	if x != nil {
		return x.Field1
	}
	return ""
}

func (x *FindMediaByHashResponseField1TypeField2TypeField2TypeField6TypeField2Type) GetField3() string {
	if x != nil {
		return x.Field3
	}
	return ""
}

var File___proto_hash_lookup_proto protoreflect.FileDescriptor

const file___proto_hash_lookup_proto_rawDesc = "" +
	"\n" +
	"\x18.proto/hash_lookup.proto\"\xb1\x02\n" +
	"\x16FindMediaByHashRequest\x12;\n" +
	"\x06field1\x18\x01 \x01(\v2#.FindMediaByHashRequest.field1_typeR\x06field1\x1a\xd9\x01\n" +
	"\vfield1_type\x12G\n" +
	"\x06field1\x18\x01 \x01(\v2/.FindMediaByHashRequest.field1_type.field1_typeR\x06field1\x12G\n" +
	"\x06field2\x18\x02 \x01(\v2/.FindMediaByHashRequest.field1_type.field2_typeR\x06field2\x1a)\n" +
	"\vfield1_type\x12\x1a\n" +
	"\bsha1Hash\x18\x01 \x01(\fR\bsha1Hash\x1a\r\n" +
	"\vfield2_type\"\x82\x06\n" +
	"\x17FindMediaByHashResponse\x12<\n" +
	"\x06field1\x18\x01 \x01(\v2$.FindMediaByHashResponse.field1_typeR\x06field1\x1a\xa8\x05\n" +
	"\vfield1_type\x12H\n" +
	"\x06field2\x18\x02 \x01(\v20.FindMediaByHashResponse.field1_type.field2_typeR\x06field2\x1a\xce\x04\n" +
	"\vfield2_type\x12T\n" +
	"\x06field1\x18\x01 \x01(\v2<.FindMediaByHashResponse.field1_type.field2_type.field1_typeR\x06field1\x12T\n" +
	"\x06field2\x18\x02 \x01(\v2<.FindMediaByHashResponse.field1_type.field2_type.field2_typeR\x06field2\x1a*\n" +
	"\vfield1_type\x12\x1b\n" +
	"\tsha1_hash\x18\x01 \x01(\fR\bsha1Hash\x1a\xe6\x02\n" +
	"\vfield2_type\x12\x1b\n" +
	"\tmedia_key\x18\x01 \x01(\tR\bmediaKey\x12`\n" +
	"\x06field6\x18\x06 \x01(\v2H.FindMediaByHashResponse.field1_type.field2_type.field2_type.field6_typeR\x06field6\x1a\xd7\x01\n" +
	"\vfield6_type\x12\x1b\n" +
	"\tmedia_key\x18\x01 \x01(\tR\bmediaKey\x12l\n" +
	"\x06field2\x18\x02 \x01(\v2T.FindMediaByHashResponse.field1_type.field2_type.field2_type.field6_type.field2_typeR\x06field2\x1a=\n" +
	"\vfield2_type\x12\x16\n" +
	"\x06field1\x18\x01 \x01(\tR\x06field1\x12\x16\n" +
	"\x06field3\x18\x03 \x01(\tR\x06field3B.Z,github.com/viperadnan-git/go-gpm/internal/pbb\x06proto3"

var (
	file___proto_hash_lookup_proto_rawDescOnce sync.Once
	file___proto_hash_lookup_proto_rawDescData []byte
)

func file___proto_hash_lookup_proto_rawDescGZIP() []byte {
	file___proto_hash_lookup_proto_rawDescOnce.Do(func() {
		file___proto_hash_lookup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file___proto_hash_lookup_proto_rawDesc), len(file___proto_hash_lookup_proto_rawDesc)))
	})
	return file___proto_hash_lookup_proto_rawDescData
}

var file___proto_hash_lookup_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file___proto_hash_lookup_proto_goTypes = []any{
	(*FindMediaByHashRequest)(nil),                                                    // 0: FindMediaByHashRequest
	(*FindMediaByHashResponse)(nil),                                                   // 1: FindMediaByHashResponse
	(*FindMediaByHashRequestField1Type)(nil),                                          // 2: FindMediaByHashRequest.field1_type
	(*FindMediaByHashRequestField1TypeField1Type)(nil),                                // 3: FindMediaByHashRequest.field1_type.field1_type
	(*FindMediaByHashRequestField1TypeField2Type)(nil),                                // 4: FindMediaByHashRequest.field1_type.field2_type
	(*FindMediaByHashResponseField1Type)(nil),                                         // 5: FindMediaByHashResponse.field1_type
	(*FindMediaByHashResponseField1TypeField2Type)(nil),                               // 6: FindMediaByHashResponse.field1_type.field2_type
	(*FindMediaByHashResponseField1TypeField2TypeField1Type)(nil),                     // 7: FindMediaByHashResponse.field1_type.field2_type.field1_type
	(*FindMediaByHashResponseField1TypeField2TypeField2Type)(nil),                     // 8: FindMediaByHashResponse.field1_type.field2_type.field2_type
	(*FindMediaByHashResponseField1TypeField2TypeField2TypeField6Type)(nil),           // 9: FindMediaByHashResponse.field1_type.field2_type.field2_type.field6_type
	(*FindMediaByHashResponseField1TypeField2TypeField2TypeField6TypeField2Type)(nil), // 10: FindMediaByHashResponse.field1_type.field2_type.field2_type.field6_type.field2_type
}
var file___proto_hash_lookup_proto_depIdxs = []int32{
	2,  // 0: FindMediaByHashRequest.field1:type_name -> FindMediaByHashRequest.field1_type
	5,  // 1: FindMediaByHashResponse.field1:type_name -> FindMediaByHashResponse.field1_type
	3,  // 2: FindMediaByHashRequest.field1_type.field1:type_name -> FindMediaByHashRequest.field1_type.field1_type
	4,  // 3: FindMediaByHashRequest.field1_type.field2:type_name -> FindMediaByHashRequest.field1_type.field2_type
	6,  // 4: FindMediaByHashResponse.field1_type.field2:type_name -> FindMediaByHashResponse.field1_type.field2_type
	7,  // 5: FindMediaByHashResponse.field1_type.field2_type.field1:type_name -> FindMediaByHashResponse.field1_type.field2_type.field1_type
	8,  // 6: FindMediaByHashResponse.field1_type.field2_type.field2:type_name -> FindMediaByHashResponse.field1_type.field2_type.field2_type
	9,  // 7: FindMediaByHashResponse.field1_type.field2_type.field2_type.field6:type_name -> FindMediaByHashResponse.field1_type.field2_type.field2_type.field6_type
	10, // 8: FindMediaByHashResponse.field1_type.field2_type.field2_type.field6_type.field2:type_name -> FindMediaByHashResponse.field1_type.field2_type.field2_type.field6_type.field2_type
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file___proto_hash_lookup_proto_init() }
func file___proto_hash_lookup_proto_init() {
	if File___proto_hash_lookup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file___proto_hash_lookup_proto_rawDesc), len(file___proto_hash_lookup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file___proto_hash_lookup_proto_goTypes,
		DependencyIndexes: file___proto_hash_lookup_proto_depIdxs,
		MessageInfos:      file___proto_hash_lookup_proto_msgTypes,
	}.Build()
	File___proto_hash_lookup_proto = out.File
	file___proto_hash_lookup_proto_goTypes = nil
	file___proto_hash_lookup_proto_depIdxs = nil
}
