// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: .proto/trash.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrashActionType int32

const (
	TrashActionType_TRASH_ACTION_UNSPECIFIED TrashActionType = 0 // Required for proto3, not used
	TrashActionType_MOVE_TO_TRASH            TrashActionType = 1 // Move items to trash
	TrashActionType_PERMANENT_DELETE         TrashActionType = 2 // Permanently delete items immediately
	TrashActionType_RESTORE_FROM_TRASH       TrashActionType = 3 // Restore items from trash
)

// Enum value maps for TrashActionType.
var (
	TrashActionType_name = map[int32]string{
		0: "TRASH_ACTION_UNSPECIFIED",
		1: "MOVE_TO_TRASH",
		2: "PERMANENT_DELETE",
		3: "RESTORE_FROM_TRASH",
	}
	TrashActionType_value = map[string]int32{
		"TRASH_ACTION_UNSPECIFIED": 0,
		"MOVE_TO_TRASH":            1,
		"PERMANENT_DELETE":         2,
		"RESTORE_FROM_TRASH":       3,
	}
)

func (x TrashActionType) Enum() *TrashActionType {
	p := new(TrashActionType)
	*p = x
	return p
}

func (x TrashActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrashActionType) Descriptor() protoreflect.EnumDescriptor {
	return file___proto_trash_proto_enumTypes[0].Descriptor()
}

func (TrashActionType) Type() protoreflect.EnumType {
	return &file___proto_trash_proto_enumTypes[0]
}

func (x TrashActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrashActionType.Descriptor instead.
func (TrashActionType) EnumDescriptor() ([]byte, []int) {
	return file___proto_trash_proto_rawDescGZIP(), []int{0}
}

// TrashAction performs trash operations on media items
type TrashAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    TrashActionType        `protobuf:"varint,2,opt,name=action_type,json=actionType,proto3,enum=TrashActionType" json:"action_type,omitempty"` // Type of trash operation to perform
	ItemKeys      []string               `protobuf:"bytes,3,rep,name=item_keys,json=itemKeys,proto3" json:"item_keys,omitempty"`                             // Media keys or dedup keys to operate on
	Field4        int64                  `protobuf:"varint,4,opt,name=field4,proto3" json:"field4,omitempty"`                                                // 1 for move/delete, 2 for restore
	Field8        *TrashAction_Field8    `protobuf:"bytes,8,opt,name=field8,proto3" json:"field8,omitempty"`                                                 // Additional metadata fields
	Field9        *TrashAction_Field9    `protobuf:"bytes,9,opt,name=field9,proto3" json:"field9,omitempty"`                                                 // Client version info (empty for permanent delete)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrashAction) Reset() {
	*x = TrashAction{}
	mi := &file___proto_trash_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrashAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrashAction) ProtoMessage() {}

func (x *TrashAction) ProtoReflect() protoreflect.Message {
	mi := &file___proto_trash_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrashAction.ProtoReflect.Descriptor instead.
func (*TrashAction) Descriptor() ([]byte, []int) {
	return file___proto_trash_proto_rawDescGZIP(), []int{0}
}

func (x *TrashAction) GetActionType() TrashActionType {
	if x != nil {
		return x.ActionType
	}
	return TrashActionType_TRASH_ACTION_UNSPECIFIED
}

func (x *TrashAction) GetItemKeys() []string {
	if x != nil {
		return x.ItemKeys
	}
	return nil
}

func (x *TrashAction) GetField4() int64 {
	if x != nil {
		return x.Field4
	}
	return 0
}

func (x *TrashAction) GetField8() *TrashAction_Field8 {
	if x != nil {
		return x.Field8
	}
	return nil
}

func (x *TrashAction) GetField9() *TrashAction_Field9 {
	if x != nil {
		return x.Field9
	}
	return nil
}

type TrashAction_Field8 struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Field4        *TrashAction_Field8_Field4 `protobuf:"bytes,4,opt,name=field4,proto3" json:"field4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrashAction_Field8) Reset() {
	*x = TrashAction_Field8{}
	mi := &file___proto_trash_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrashAction_Field8) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrashAction_Field8) ProtoMessage() {}

func (x *TrashAction_Field8) ProtoReflect() protoreflect.Message {
	mi := &file___proto_trash_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrashAction_Field8.ProtoReflect.Descriptor instead.
func (*TrashAction_Field8) Descriptor() ([]byte, []int) {
	return file___proto_trash_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TrashAction_Field8) GetField4() *TrashAction_Field8_Field4 {
	if x != nil {
		return x.Field4
	}
	return nil
}

type TrashAction_Field9 struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Field1        int64                      `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"` // Constant: 5
	Field2        *TrashAction_Field9_Field2 `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`  // Client version details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrashAction_Field9) Reset() {
	*x = TrashAction_Field9{}
	mi := &file___proto_trash_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrashAction_Field9) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrashAction_Field9) ProtoMessage() {}

func (x *TrashAction_Field9) ProtoReflect() protoreflect.Message {
	mi := &file___proto_trash_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrashAction_Field9.ProtoReflect.Descriptor instead.
func (*TrashAction_Field9) Descriptor() ([]byte, []int) {
	return file___proto_trash_proto_rawDescGZIP(), []int{0, 1}
}

func (x *TrashAction_Field9) GetField1() int64 {
	if x != nil {
		return x.Field1
	}
	return 0
}

func (x *TrashAction_Field9) GetField2() *TrashAction_Field9_Field2 {
	if x != nil {
		return x.Field2
	}
	return nil
}

type TrashAction_Field8_Field4 struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Field2        *TrashAction_Field8_Field4_Empty  `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"` // Empty metadata field
	Field3        *TrashAction_Field8_Field4_Field3 `protobuf:"bytes,3,opt,name=field3,proto3" json:"field3,omitempty"` // Nested metadata
	Field4        *TrashAction_Field8_Field4_Empty  `protobuf:"bytes,4,opt,name=field4,proto3" json:"field4,omitempty"` // Empty metadata field (only for move/delete)
	Field5        *TrashAction_Field8_Field4_Field5 `protobuf:"bytes,5,opt,name=field5,proto3" json:"field5,omitempty"` // Nested metadata (only for move/delete)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrashAction_Field8_Field4) Reset() {
	*x = TrashAction_Field8_Field4{}
	mi := &file___proto_trash_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrashAction_Field8_Field4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrashAction_Field8_Field4) ProtoMessage() {}

func (x *TrashAction_Field8_Field4) ProtoReflect() protoreflect.Message {
	mi := &file___proto_trash_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrashAction_Field8_Field4.ProtoReflect.Descriptor instead.
func (*TrashAction_Field8_Field4) Descriptor() ([]byte, []int) {
	return file___proto_trash_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *TrashAction_Field8_Field4) GetField2() *TrashAction_Field8_Field4_Empty {
	if x != nil {
		return x.Field2
	}
	return nil
}

func (x *TrashAction_Field8_Field4) GetField3() *TrashAction_Field8_Field4_Field3 {
	if x != nil {
		return x.Field3
	}
	return nil
}

func (x *TrashAction_Field8_Field4) GetField4() *TrashAction_Field8_Field4_Empty {
	if x != nil {
		return x.Field4
	}
	return nil
}

func (x *TrashAction_Field8_Field4) GetField5() *TrashAction_Field8_Field4_Field5 {
	if x != nil {
		return x.Field5
	}
	return nil
}

type TrashAction_Field8_Field4_Field3 struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Field1        *TrashAction_Field8_Field4_Empty `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrashAction_Field8_Field4_Field3) Reset() {
	*x = TrashAction_Field8_Field4_Field3{}
	mi := &file___proto_trash_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrashAction_Field8_Field4_Field3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrashAction_Field8_Field4_Field3) ProtoMessage() {}

func (x *TrashAction_Field8_Field4_Field3) ProtoReflect() protoreflect.Message {
	mi := &file___proto_trash_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrashAction_Field8_Field4_Field3.ProtoReflect.Descriptor instead.
func (*TrashAction_Field8_Field4_Field3) Descriptor() ([]byte, []int) {
	return file___proto_trash_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *TrashAction_Field8_Field4_Field3) GetField1() *TrashAction_Field8_Field4_Empty {
	if x != nil {
		return x.Field1
	}
	return nil
}

type TrashAction_Field8_Field4_Field5 struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Field1        *TrashAction_Field8_Field4_Empty `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrashAction_Field8_Field4_Field5) Reset() {
	*x = TrashAction_Field8_Field4_Field5{}
	mi := &file___proto_trash_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrashAction_Field8_Field4_Field5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrashAction_Field8_Field4_Field5) ProtoMessage() {}

func (x *TrashAction_Field8_Field4_Field5) ProtoReflect() protoreflect.Message {
	mi := &file___proto_trash_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrashAction_Field8_Field4_Field5.ProtoReflect.Descriptor instead.
func (*TrashAction_Field8_Field4_Field5) Descriptor() ([]byte, []int) {
	return file___proto_trash_proto_rawDescGZIP(), []int{0, 0, 0, 1}
}

func (x *TrashAction_Field8_Field4_Field5) GetField1() *TrashAction_Field8_Field4_Empty {
	if x != nil {
		return x.Field1
	}
	return nil
}

type TrashAction_Field8_Field4_Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrashAction_Field8_Field4_Empty) Reset() {
	*x = TrashAction_Field8_Field4_Empty{}
	mi := &file___proto_trash_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrashAction_Field8_Field4_Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrashAction_Field8_Field4_Empty) ProtoMessage() {}

func (x *TrashAction_Field8_Field4_Empty) ProtoReflect() protoreflect.Message {
	mi := &file___proto_trash_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrashAction_Field8_Field4_Empty.ProtoReflect.Descriptor instead.
func (*TrashAction_Field8_Field4_Empty) Descriptor() ([]byte, []int) {
	return file___proto_trash_proto_rawDescGZIP(), []int{0, 0, 0, 2}
}

type TrashAction_Field9_Field2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field1        int64                  `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"` // Client version code
	Field2        string                 `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`  // Android API version as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrashAction_Field9_Field2) Reset() {
	*x = TrashAction_Field9_Field2{}
	mi := &file___proto_trash_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrashAction_Field9_Field2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrashAction_Field9_Field2) ProtoMessage() {}

func (x *TrashAction_Field9_Field2) ProtoReflect() protoreflect.Message {
	mi := &file___proto_trash_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrashAction_Field9_Field2.ProtoReflect.Descriptor instead.
func (*TrashAction_Field9_Field2) Descriptor() ([]byte, []int) {
	return file___proto_trash_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *TrashAction_Field9_Field2) GetField1() int64 {
	if x != nil {
		return x.Field1
	}
	return 0
}

func (x *TrashAction_Field9_Field2) GetField2() string {
	if x != nil {
		return x.Field2
	}
	return ""
}

var File___proto_trash_proto protoreflect.FileDescriptor

const file___proto_trash_proto_rawDesc = "" +
	"\n" +
	"\x12.proto/trash.proto\"\xa5\x06\n" +
	"\vTrashAction\x121\n" +
	"\vaction_type\x18\x02 \x01(\x0e2\x10.TrashActionTypeR\n" +
	"actionType\x12\x1b\n" +
	"\titem_keys\x18\x03 \x03(\tR\bitemKeys\x12\x16\n" +
	"\x06field4\x18\x04 \x01(\x03R\x06field4\x12+\n" +
	"\x06field8\x18\b \x01(\v2\x13.TrashAction.Field8R\x06field8\x12+\n" +
	"\x06field9\x18\t \x01(\v2\x13.TrashAction.Field9R\x06field9\x1a\xc2\x03\n" +
	"\x06Field8\x122\n" +
	"\x06field4\x18\x04 \x01(\v2\x1a.TrashAction.Field8.Field4R\x06field4\x1a\x83\x03\n" +
	"\x06Field4\x128\n" +
	"\x06field2\x18\x02 \x01(\v2 .TrashAction.Field8.Field4.EmptyR\x06field2\x129\n" +
	"\x06field3\x18\x03 \x01(\v2!.TrashAction.Field8.Field4.Field3R\x06field3\x128\n" +
	"\x06field4\x18\x04 \x01(\v2 .TrashAction.Field8.Field4.EmptyR\x06field4\x129\n" +
	"\x06field5\x18\x05 \x01(\v2!.TrashAction.Field8.Field4.Field5R\x06field5\x1aB\n" +
	"\x06Field3\x128\n" +
	"\x06field1\x18\x01 \x01(\v2 .TrashAction.Field8.Field4.EmptyR\x06field1\x1aB\n" +
	"\x06Field5\x128\n" +
	"\x06field1\x18\x01 \x01(\v2 .TrashAction.Field8.Field4.EmptyR\x06field1\x1a\a\n" +
	"\x05Empty\x1a\x8e\x01\n" +
	"\x06Field9\x12\x16\n" +
	"\x06field1\x18\x01 \x01(\x03R\x06field1\x122\n" +
	"\x06field2\x18\x02 \x01(\v2\x1a.TrashAction.Field9.Field2R\x06field2\x1a8\n" +
	"\x06Field2\x12\x16\n" +
	"\x06field1\x18\x01 \x01(\x03R\x06field1\x12\x16\n" +
	"\x06field2\x18\x02 \x01(\tR\x06field2*p\n" +
	"\x0fTrashActionType\x12\x1c\n" +
	"\x18TRASH_ACTION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rMOVE_TO_TRASH\x10\x01\x12\x14\n" +
	"\x10PERMANENT_DELETE\x10\x02\x12\x16\n" +
	"\x12RESTORE_FROM_TRASH\x10\x03B.Z,github.com/viperadnan-git/go-gpm/internal/pbb\x06proto3"

var (
	file___proto_trash_proto_rawDescOnce sync.Once
	file___proto_trash_proto_rawDescData []byte
)

func file___proto_trash_proto_rawDescGZIP() []byte {
	file___proto_trash_proto_rawDescOnce.Do(func() {
		file___proto_trash_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file___proto_trash_proto_rawDesc), len(file___proto_trash_proto_rawDesc)))
	})
	return file___proto_trash_proto_rawDescData
}

var file___proto_trash_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file___proto_trash_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file___proto_trash_proto_goTypes = []any{
	(TrashActionType)(0),                     // 0: TrashActionType
	(*TrashAction)(nil),                      // 1: TrashAction
	(*TrashAction_Field8)(nil),               // 2: TrashAction.Field8
	(*TrashAction_Field9)(nil),               // 3: TrashAction.Field9
	(*TrashAction_Field8_Field4)(nil),        // 4: TrashAction.Field8.Field4
	(*TrashAction_Field8_Field4_Field3)(nil), // 5: TrashAction.Field8.Field4.Field3
	(*TrashAction_Field8_Field4_Field5)(nil), // 6: TrashAction.Field8.Field4.Field5
	(*TrashAction_Field8_Field4_Empty)(nil),  // 7: TrashAction.Field8.Field4.Empty
	(*TrashAction_Field9_Field2)(nil),        // 8: TrashAction.Field9.Field2
}
var file___proto_trash_proto_depIdxs = []int32{
	0,  // 0: TrashAction.action_type:type_name -> TrashActionType
	2,  // 1: TrashAction.field8:type_name -> TrashAction.Field8
	3,  // 2: TrashAction.field9:type_name -> TrashAction.Field9
	4,  // 3: TrashAction.Field8.field4:type_name -> TrashAction.Field8.Field4
	8,  // 4: TrashAction.Field9.field2:type_name -> TrashAction.Field9.Field2
	7,  // 5: TrashAction.Field8.Field4.field2:type_name -> TrashAction.Field8.Field4.Empty
	5,  // 6: TrashAction.Field8.Field4.field3:type_name -> TrashAction.Field8.Field4.Field3
	7,  // 7: TrashAction.Field8.Field4.field4:type_name -> TrashAction.Field8.Field4.Empty
	6,  // 8: TrashAction.Field8.Field4.field5:type_name -> TrashAction.Field8.Field4.Field5
	7,  // 9: TrashAction.Field8.Field4.Field3.field1:type_name -> TrashAction.Field8.Field4.Empty
	7,  // 10: TrashAction.Field8.Field4.Field5.field1:type_name -> TrashAction.Field8.Field4.Empty
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file___proto_trash_proto_init() }
func file___proto_trash_proto_init() {
	if File___proto_trash_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file___proto_trash_proto_rawDesc), len(file___proto_trash_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file___proto_trash_proto_goTypes,
		DependencyIndexes: file___proto_trash_proto_depIdxs,
		EnumInfos:         file___proto_trash_proto_enumTypes,
		MessageInfos:      file___proto_trash_proto_msgTypes,
	}.Build()
	File___proto_trash_proto = out.File
	file___proto_trash_proto_goTypes = nil
	file___proto_trash_proto_depIdxs = nil
}
